# Generated by Django 2.0 on 2018-01-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20171225_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='localization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
