# Generated by Django 2.0 on 2018-01-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_car_localization'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_models',
            field=models.CharField(choices=[('BE', 'Berline'), ('CO', 'Coupé'), ('CA', 'Cabriolet'), ('RA', 'Roadster'), ('KA', '4X4'), ('SU', 'Suv'), ('CR', 'Crossover'), ('BR', 'Break'), ('MO', 'Monospace')], default='BE', max_length=2),
        ),
    ]
