# Generated by Django 2.0.1 on 2018-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_auto_20180203_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='daily_rent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
