# Generated by Django 2.0.2 on 2018-02-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_auto_20180207_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='daily_rent',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
