# Generated by Django 2.0.2 on 2018-08-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180818_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(choices=[('GE', 'General'), ('GR', 'Greeting'), ('DI', 'Dislike'), ('LI', 'Like')], default='GE', max_length=2),
        ),
    ]
