# Generated by Django 2.0.2 on 2018-08-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ('published_date',), 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AddField(
            model_name='annonce',
            name='contact_email',
            field=models.EmailField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='job_offer',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('FRE', 'Freelance'), ('STA', 'Stage'), ('ALT', 'Alternance')], default='CDI', max_length=3),
        ),
        migrations.AddField(
            model_name='annonce',
            name='job_time',
            field=models.CharField(choices=[('FULL', 'Temps plein'), ('HALF', 'Temps partiel')], default='FULL', max_length=4),
        ),
        migrations.AddField(
            model_name='annonce',
            name='language',
            field=models.CharField(choices=[('FR', 'French'), ('EN', 'English')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='annonce',
            name='localization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='url_redirection',
            field=models.URLField(blank=True, max_length=740),
        ),
    ]
