# Generated by Django 2.0.2 on 2018-08-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_auto_20180819_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='job_time',
        ),
        migrations.AddField(
            model_name='annonce',
            name='job_fields',
            field=models.CharField(choices=[('UI', 'UI design'), ('FE', 'Front-end development'), ('BA', 'Back-end development'), ('AP', 'App Development'), ('AR', 'Information Architecture'), ('CS', 'Content Strategy'), ('MA', 'Management'), ('SM', 'Social Media Expert'), ('MI', 'Miscellary')], default='UI', max_length=2),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='job_offer',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('FRE', 'Freelance'), ('STA', 'Stage'), ('ALT', 'Alternance'), ('FUL', 'Temps plein'), ('HAL', 'Temps partiel')], default='CDI', max_length=3),
        ),
    ]
